# Generated by Django 4.2.1 on 2023-05-03 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='accounts',
        ),
        migrations.AddField(
            model_name='invoice',
            name='month_reference',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoice')),
            ],
        ),
    ]
