# Generated by Django 4.2.1 on 2023-05-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_value',
            field=models.FloatField(),
        ),
    ]
