# Generated by Django 4.2.1 on 2023-05-04 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_account_account_type_alter_account_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
    ]
