# Generated by Django 4.2.1 on 2023-05-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_account_invoiced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='responsible_email',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='responsible_name',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='responsible_phone',
        ),
    ]
