# Generated by Django 4.2.1 on 2023-05-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_owner_remove_apartment_responsible_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Person',
        ),
    ]
