# Generated by Django 4.2.1 on 2023-05-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_account_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.IntegerField(choices=[(1, 'Eletricidade'), (2, 'Água'), (3, 'Gás'), (4, 'Limpeza'), (5, 'Jardim'), (6, 'Outro')], default=6),
        ),
    ]
