# Generated by Django 4.2.1 on 2023-05-04 03:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_account_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('category', models.IntegerField(choices=[(1, 'Eletricidade'), (2, 'Água'), (3, 'Gás'), (4, 'Limpeza'), (5, 'Jardim'), (6, 'Outro')], default=6)),
                ('due_date', models.DateField(default=datetime.date(2023, 5, 10))),
                ('expense_type', models.IntegerField(choices=[(1, 'Compartilhada'), (2, 'Exclusiva')], default=2)),
                ('invoiced', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apartment')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='expense',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.expense'),
            preserve_default=False,
        ),
    ]
