# Generated by Django 4.2.1 on 2023-05-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.IntegerField(choices=[(1, 'Energia'), (2, 'Água'), (3, 'Gás'), (4, 'Limpeza'), (5, 'Jardim'), (6, 'Reserva'), (7, 'Outro')], default=7),
        ),
    ]
