# Generated by Django 4.2.1 on 2023-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_cashflow_account_cashflow_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='type',
            field=models.IntegerField(choices=[(1, 'Entradas'), (2, 'Saídas')], max_length=10),
        ),
    ]
