# Generated by Django 4.2.1 on 2023-05-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_cashflow_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='cashflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cashflow'),
        ),
    ]
